### ISSUE TITLE
Tag 0.2.0 release

### ISSUE THREAD

**Issue by gilch** [gilch/hissp#83]
I want to feature freeze for the alpha release, preferably this week.

- [x] Fix or at least work around missing indexes in docs #75
- [x] Remove linked list emulation macros #84 
- [x] Document main in reader.py (related to #24)
- [x] Copy edit pass for docs #87

No more tutorials or macros before release.

**Comment by gilch** [comment]
Once that's done, do the release process.

- [ ] Ensure package builder (setup.py) is up to date, including version number and classifiers
- [ ] tag and manually test build on test PyPI
- [ ] Install from PyPI in a fresh environment
- [ ] tag and release on PyPI

**Comment by gilch** [comment]
OMG _why_ is Python packaging this difficult? Can't find good documentation. Setuptools doesn't include your files, then pip put files in the wrong places. Pre-release versions apparently no longer work with pip. You have to get everything 100% right on your first try. No grace period, no takebacks, no pre-releases. I can at least use test-pypi, but still, no pre-releases. I can't use the real versions. They keep changing the rules. PyPI renders emdashes as mojibake, and apparently requires images to be hosted elsewhere. Ugh.

**Comment by gilch** [comment]
It is done.
